pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                   
                    sh '''
                        #!/bin/bash 
                        pwd 
                        ls
                        echo "This is a BUILD stage"
                        
                    ''' 
            }
        }
    }
}
